# Generated by Django 5.2.9 on 2026-01-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_alias', models.CharField(max_length=100)),
                ('intercepted_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nodes_discovered', models.IntegerField(default=0)),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subject Scan Log',
                'ordering': ['-scan_timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ScanLog',
        ),
    ]
